import type { ReactNode } from 'react';
import { Archive, Info, Palette, Settings } from 'lucide-react';
import { PageHeader } from '../components/ui';
import { Field } from '../components/fields';
import type { StoredSettings } from '../core/types';
import { THEME_LABELS, THEME_PREFERENCES, type ThemePreference } from '../core/theme';

export function SettingsPage({ settings, onChange, onRestore, onPrivacy, onExport, onImport, theme, onThemeChange, cloud }: { settings: StoredSettings; onChange: (key: keyof StoredSettings, value: string) => void; onRestore: () => void; onPrivacy: () => void; onExport: () => void; onImport: () => void; theme: ThemePreference; onThemeChange: (value: ThemePreference) => void; cloud?: ReactNode }) {
  return <>
    <PageHeader kicker="PREFERÊNCIAS LOCAIS" title="Configurações" description="Estes valores são usados como ponto de partida nos novos orçamentos e ficam salvos neste dispositivo." />
    <section className="settings-panel panel-card"><div className="settings-section-title"><Settings size={18} /><div><h2>Parâmetros padrão</h2><p>Custos aplicados a cada novo cálculo</p></div></div><Field label="Energia (R$/kWh)" value={settings.energyPricePerKwh} onChange={(value) => onChange('energyPricePerKwh', value)} /><Field label="Mão de obra (R$/h)" value={settings.laborCostPerHour} onChange={(value) => onChange('laborCostPerHour', value)} /><Field label="Embalagem (R$)" value={settings.packaging} onChange={(value) => onChange('packaging', value)} /><Field label="Margem (%)" value={settings.marginPercent} onChange={(value) => onChange('marginPercent', value)} /></section>
    <section className="settings-note"><Info size={18} /><div><strong>Persistência local ativa</strong><span>Materiais, impressoras, configurações e históricos ficam neste aparelho, com cópia no armazenamento nativo do Android.</span></div></section>
    <section className="settings-panel panel-card"><div className="settings-section-title"><Palette size={18} /><div><h2>Aparência</h2><p>Vale só para este aparelho</p></div></div><div className="theme-switch" role="group" aria-label="Tema do aplicativo">{THEME_PREFERENCES.map((option) => <button key={option} type="button" className={option === theme ? 'active' : undefined} aria-pressed={option === theme} onClick={() => onThemeChange(option)}>{THEME_LABELS[option]}</button>)}</div></section>
    <section className="settings-panel panel-card"><div className="settings-section-title"><Archive size={18} /><div><h2>Backup</h2><p>Um arquivo com todo o seu catálogo e histórico</p></div></div><div className="settings-actions"><button className="secondary-button" type="button" onClick={onExport}>Exportar backup</button><button className="secondary-button" type="button" onClick={onImport}>Importar backup</button></div><p className="settings-hint">Importar substitui os dados atuais deste aparelho. As fotos dos orçamentos ficam só neste aparelho e não entram no arquivo de backup — elas vão na cópia da nuvem.</p></section>
    {cloud}
    <div className="settings-actions"><button className="secondary-button" type="button" onClick={onRestore}>Restaurar parâmetros padrão</button><button className="secondary-button" type="button" onClick={onPrivacy}>Política de privacidade</button></div>
  </>;
}

export function PrivacyPage({ onBack }: { onBack: () => void }) {
  return <section className="privacy-page panel-card"><button className="back-button" type="button" onClick={onBack}>← Voltar</button><span className="section-kicker">TRANSPARÊNCIA</span><h1>Política de privacidade</h1><p>O PrintForge foi projetado para funcionar offline e sem necessidade de conta na versão atual.</p><h2>Dados armazenados</h2><p>O aplicativo armazena localmente no dispositivo os dados inseridos pelo usuário, incluindo materiais, impressoras, configurações, históricos de cálculo e o controle de estoque — as bobinas cadastradas e o extrato de baixas e ajustes de cada uma.</p><h2>Compartilhamento</h2><p>Os dados não são enviados para servidores externos pelo PrintForge. Quando você usa a função de compartilhar um orçamento, o conteúdo é entregue ao recurso de compartilhamento do sistema operacional escolhido por você.</p><h2>Acesso à internet</h2><p>O aplicativo funciona sem conexão. A única exceção é anexar a foto de um orçamento por endereço de internet: aí o aplicativo baixa a imagem, e o site que a hospeda vê que este aparelho pediu o arquivo. Nada do seu orçamento, catálogo ou estoque vai junto. Quem usa câmera ou galeria nunca aciona esse caminho.</p><h2>Backup</h2><p>Ao exportar um backup, o arquivo é gerado neste aparelho e entregue à folha de compartilhamento do sistema. Você escolhe o destino; o PrintForge não envia o arquivo a lugar algum.</p><h2>Controle do usuário</h2><p>Você pode remover materiais, impressoras, cálculos e bobinas pelo próprio aplicativo — remover uma bobina apaga também o extrato dela. A limpeza completa dos dados pode ser feita nas configurações do armazenamento do dispositivo.</p><p className="privacy-updated">Última atualização: setembro de 2026</p></section>;
}
